#!/bin/sh

#===============================================================================
# Snow Leopard Compiler Project
#
# Copyright (C) 2012 Roel Sergeant
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more 
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>
#===============================================================================

#-------------------------------------------------------------------------------
# user_manual_to_man
#-------------------------------------------------------------------------------
# This script extract the manpage part of the user manual for each tool/library.
# It works by finding the relevant parts of the user manual and creating a new
# troff file containing the manual page for the tool.
#-------------------------------------------------------------------------------
# Script arguments
#-------------------------------------------------------------------------------

. ./../../common/scripts/common.sh
