/*==============================================================================
  Snow Leopard Standard C Library
  
  Copyright (C) 2008, 2009, 2010, 2011, 2012 Roel Sergeant
  
  This program is free software: you can redistribute it and/or modify it under
  the terms of the GNU General Public License as published by the Free
  Software Foundation, either version 3 of the License, or (at your option) any
  later version
  
  This program is distributed in the hope that it will be useful, but WITHOUT
  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
  FOR A PARTICULAR PURPOSE. See the GNU General Public License for more 
  details.
  
  You should have received a copy of the GNU General Public License along with
  this program. If not, see <http://www.gnu.org/licenses/>
  ============================================================================*/

//------------------------------------------------------------------------------
// program_startup.c
//------------------------------------------------------------------------------
// Standard error handling implementation
//------------------------------------------------------------------------------

#include <sl/config/config.h>

#include <sl/stdc/private/ll_open_files.h>
#include <sl/stdc/private/program_globals.h>
#include <sl/stdc/private/stdio_private.h>

#include <sl/stdc/program_startup.h>

#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

//------------------------------------------------------------------------------
// _SL_Main function
//
// This function is called by the code generated by the compiler to create the
// executable. After program initialization it calls the main function.
int _SL_Main() {
  int retval = 0;
  int argc = 0;
  char** argv = NULL;

  /* Setup standard streams */
  if(__SL_NoStandardStreams == 0)
    _sl_startup_initialize_standard_streams();

  /* Call main after initialization */
  retval = main(argc, argv);

  /* Call _SL_Terminate */
  retval = _SL_Terminate(retval);

  return retval;
}
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
// _SL_Terminate function
//
// This function performs program cleanup and termination.
int _SL_Terminate(int retval) {
  /* Flush and destroy open files */
  sl_ll_of_node_* node = __SL_OpenFiles->first_;
  FILE* stream;
      
  while(node->next_ != NULL) {
    stream = (FILE*)node->node_;
    fclose(stream);
    node = node->next_;
    _sl_ll_remove_of(__SL_OpenFiles, node->prev_);
  }

  stdin = NULL;
  stdout = NULL;
  stderr = NULL;
  
  return retval;
}
//------------------------------------------------------------------------------

//-<EOF>
