#!/bin/sh

#===============================================================================
# Snow Leopard Project Website
#
# Copyright (C) 2012 Roel Sergeant
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more 
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>
#===============================================================================

#-------------------------------------------------------------------------------
# publish_site
#-------------------------------------------------------------------------------
# This script copies the website from the source control tree to its publish
# location.
#-------------------------------------------------------------------------------
# Script arguments
#   --path <path> Root location of the websites publish location. If not
#                 specified it defaults to ~/public_html.
#   --reset Reset values stored in datafiles to their default values.
#-------------------------------------------------------------------------------

#-<EOF>
