#!/bin/sh

#===============================================================================
# Lynx Typesetting System
#
# Copyright (C) 2010, 2011, 2012 Roel Sergeant
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more 
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>
#===============================================================================

#-------------------------------------------------------------------------------
# lynxc
#-------------------------------------------------------------------------------
# This script executes the Lynx checker on the provided set of files to verify
# the syntax and semantics of the files provided.
#
# It is executed during build of the Lynx system to check that the macro files
# are correct.
#-------------------------------------------------------------------------------
# Script arguments
#   <files>       - Files to run through the checker.
#   <+->leqn      - Force/use eqn syntax.
#   <+->lmetafont - Force/use MetaFont syntax.
#   <+->lpic      - Force/use pic syntax.
#   <+->lrefer    - Force/use refer syntax.
#   <+->lroff     - Force/use roff syntax.
#   <+->lsoelim   - Force/use soelim syntax.
#   <+->ltex      - Force/use TeX syntax.
#   <+->ltbl      - Force/use ltbl syntax. 
#-------------------------------------------------------------------------------

#-<EOF>
