#!/bin/sh


#===============================================================================
# Snow Leopard Build Tool
#
# Copyright (C) 2012 Roel Sergeant
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more 
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>
#===============================================================================

#-------------------------------------------------------------------------------
# slbld
#-------------------------------------------------------------------------------
# This script is executed when a standard Unix C compiler is needed. It calls 
# slcc transforming SUSv4 compliant arguments into native slcc commands.
#-------------------------------------------------------------------------------
# Script arguments (POSIX)
#-------------------------------------------------------------------------------

#-<EOF>
